---
name: Video-FourCC-Info
version: 1.001007
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: |-
  Find information about codecs from its FourCC
license: unrestricted
requires:
  Carp: 1.04
  DBD::SQLite: 1.20
  DBI: 0
  File::Basename: 0
  File::Spec: 0
  perl: 5.006
  strict: 0
  version: 0
  warnings: 0
build_requires:
  Test::More: 0.62
  Test::NoWarnings: 0.084
recommends:
  DateTime: 0
  Video::Info::Magic: 1.01
dynamic_config: 0
provides:
  Video::FourCC::Info:
    file: lib/Video/FourCC/Info.pm
    version: 1.001007
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
resources:
  Ratings: http://cpanratings.perl.org/d/Video-FourCC-Info
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Video-FourCC-Info
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Video-FourCC-Info
